sudo: required
services:
    -docker

before_install:
    - docker build -t andymac007/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true andymac007/react-test npm test

after_success:
    - docker build -t andymac007/multi-client ./client
    - docker build -t andymac007/multi-nginx ./nginx
    - docker build -t andymac007/multi-server ./server
    - docker build -t andymac007.multi-worker ./worker
    #Log in to the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    #take those images and push them to docker hub
    - docker push andymac007/multi-client
    - docker push andymac007/multi-nginx
    - docker push andymac007/multi-server
    - docker push andymac007/multi-worker